# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2011-02-16 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20110216_0123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Bags',
        ),
    ]
